spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: ${AUTH_SERVICE_URL:http://localhost:8081}
            predicates: [ Path=/auth/** ]
          - id: users
            uri: ${USER_SERVICE_URL:http://localhost:8082}
            predicates: [ Path=/users/** ]
          - id: drivers
            uri: ${DRIVER_SERVICE_URL:http://localhost:8083}
            predicates: [ Path=/drivers/** ]
          - id: rides
            uri: ${RIDE_SERVICE_URL:http://localhost:8084}
            predicates: [ Path=/rides/** ]
          - id: payments
            uri: ${PAYMENT_SERVICE_URL:http://localhost:8087}
            predicates: [ Path=/payments/** ]
          - id: tracking
            uri: ${TRACKING_SERVICE_URL:http://localhost:8088}
            predicates: [ Path=/tracking/**,/ws/** ]
